spring.application.name=geolocalizacion-service
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bd_Geo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:bastian10}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${SERVER_PORT:8082}
