spring.application.name=mascotas-service
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/bd_Mascotas
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:220206Cj*}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:v5zti3ggthj4radzaynh5q9uoezj66cl}
jwt.expiration=3600000

spring.security.user.name=admin
spring.security.user.password=1234

OCI_USER_ID=ocid1.user.oc1..aaaaaaaa7uhovjtovpwbckixajwb5hc2eolju656tajhuouvytpdvglnxpyq
OCI_TENANCY_ID=ocid1.tenancy.oc1..aaaaaaaaqyifudeykwssoesrhgsy3m2yfx7m2wkrclaieq2dzudx4ugblexq
OCI_FINGERPRINT=00:49:4b:f9:fa:bc:c4:bb:43:e5:61:1f:be:23:c0:2d
OCI_REGION=sa-santiago-1
OCI_NAMESPACE=axgfwyf4tpjt
OCI_BUCKET=Mascotas-bucket
OCI_PRIVATE_KEY_PATH=${OCI_PRIVATE_KEY_PATH:C:/Users/carlo/Documents/GitHub/SanosySalvos/mascotas-service/oci_api_key.pem}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
